config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   to: 'trashes#index'
  # resources :searches, only: [:index]
  resources :trashes, only: [:index, :show, ] do
    collection do
      get 'search'
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  # def self.search(search)
  #   return nil if input == ""
  #   Trash.where('name LIKE(?)', "%#{search}%", REGEXP '[ぁ-ん ァ-ン]')
  #  end
  

end

app/models/trash.rb
class Trash < ApplicationRecord
  def self.search(input)
    return nil if input == ""
    Trash.where(['name LIKE ?', "%#{input}%"])
  end

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
end

app/controllers/trashes_controller.rb
class TrashesController < ApplicationController
  def index
  end

  def show
    @trashes = Trash.all.order(name: :ASC, ).page(params[:page]).per(10)
  end

  
  def search
    
    @trashes = Trash.search(params[:keyword])
    # render json: @trashes      # jsonでレスポンスを返す
    respond_to do |format|
        format.html               #jsonで返せなかった時？htmlで返せる
        format.json
    end    
    # if @trashes != 0
    #   respond_to do |format|
    #     format.html 
    #     format.json
    #   end
    # else
    #   flash[:notice] = "該当するものがありませんでした。"
      
    # end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trashs_helper.rb
module TrashsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrashSeparationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name=”viewport” content=”width=device-width, initial-scale=1”>
  </head>

  <body>
  
    <%= yield %>
    
    
    
  </body>
</html>

app/views/trashes/_trash_list.html.erb
 <table>
    <tr>
      <th scope = "col">品目</th>
      <th scope = "col">分別区分</th>
      <th scope = "col">袋の区分（色）</th>
    </tr>
     
    
    <% @trashes.each do |trash| %>
      
       <tr >
          <td> <%= trash.name %> </td> 
          <td> <%= trash.separation %> </td> 
          <td> <%= trash.color_division %> </td> 
       </tr> 
      
    <% end %> 
 
  </table> 
  

app/views/trashes/index.html.erb
<div class = "header">
  <h1>menu</h1>
    <p id = "nav"><i class="fas fa-arrow-alt-circle-up "></i></p>
</div>

  <div class = "list-block">
    <div class = "f-item">
      <a href = "/trashes/show", class = "list"> ゴミ分検索 </a>
    </div> 
    <div class = "f-item">
      <a href = "#how-to-garbage", class = "list"> ゴミの出し方 </a>
    </div> 
    <div class = "f-item">
      <a href = "#question", class = "list"> よくある質問</a>
    </div> 
    <div class = "f-item">
      <a href = "#bring-in", class = "list"> ゴミの持ち込み </a>
    </div> 
    <div class = "f-item">
      <a href = "#appliance", class = "list"> 家電４品目 </a>
    </div> 
    <div class = "f-item">
      <a href = "#contact" , class = "list"> 問い合わせ先</a>
    </div>   
  </div>

  <div id = "how-to-garbage">ゴミの出し方
    <ul id = "how-to-list">
      <li class = "how-to-item">
        <h3 class = "how-to ">燃えるゴミ</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
          <p>生ゴミ、紙くず、プラスチック製の製品、繊維くず、革類、ゴムくず、木くず、草、花、しば、その他</p>
          </div>
          <div class = "explanation">
          <p>収集回数: 週2回<br>燃やすゴミの指定袋(有料)で出してください。<br>大袋（45リットル相当）の指定袋に入れて、口がしばれないものは大型ゴミです。指定袋の間違いは収集しません。</p>
          <p class = "title">出し方</p>
          <div>
            <p> 生ごみは水を切ってください。</p>
            <p>名刺より大きな紙は紙の日に出してください。</p>
            <p>草や花は燃やすゴミの指定袋で出してください。</p>
            <p>落ち葉、剪定枝については無料で収集します。<br>剪定枝は、長さ50cm以下に切って45リットルまでの透明ゴミ袋に入れるか、直径30cm以下に束ね、紐で縛って出してください。落ち葉は、45リットルまでの透明ゴミ袋で出してください。</p>
            <p>落ち葉や剪定枝はできるだけ週の後半の収集日に出してください。</p>
          </div>
          </div>
        </div>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">紙</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
          <p>新聞紙、チラシ、ダンボール、紙パック(500ml以上)、その他の紙(本、雑誌、ノート、包装紙、紙袋、カタログなど)</p>
          </div>
          <div class = "explanation">
          <p>収集回数: 週1回<br>名刺よりも大きいサイズの紙が対象です。種類ごとに紐で十字に縛って出してください。『その他の紙』は紙袋に入れて出す事も出来ます。</p>
          <p class = "title">出し方</p>
          <div>
            <p> ダンボールに入れたり粘着デープで縛ったりしないでください。</p>
            <p>セロハンやビニールは取り除いてください。</p>
            <p>次のものはリサイクルできない紙なので混ぜないでください。<br>(感熱紙、カーボン紙、写真、アイロンプリント紙、ビニールコート紙、紙コップなどのワックス加工紙、匂いのついた紙、銀紙)</p>
            <p>シュレッダーにかけた紙は、燃やすゴミに出してください。</p>
          </div>
          </div>
        </div>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">ペットボトル</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
          <p>ジュース、お茶などの清涼飲料水、乳飲料、調味料、酒などの容器で、ペットボトルマークのついたもの</p>
          </div>
          <div class = "explanation">
          <p>収集回数: 月2回<br>※ 原則として祝日の収集はありません。</p>
          <p class = "title">出し方</p>
          <div>
            <p> 45リットルまでの透明ゴミ袋で出してください。</p>
            <p>キャップとラベルは取り外して、中を軽くすすいで潰して出してください。</p>
            <p>キャップとラベルは『プラスチック製容器包装』で出してください。</p>
            <p>中にタバコの吸い殻やゴミを入れないでください。</p>
          </div>
          </div>
        </div>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">資源ごみ</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">プラスチック</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">粗大ゴミ</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
      </li>
      <div class = "break"></div>
      <li class = "how-to-item">
        <h3 class = "how-to ">その他</h3>
        <span>+</span>
        <div class = "answer">
          <div class = "main">
          <p class = "title">主なもの</p>
      </li>
      <div class = "break"></div>
      
    </ul>
  </div>
  <div class = "question-wrapper">  
    <div id = "question">
        よくある質問
      <ul id = "how-to-list">
        <div class = "how-to-item">
          <h3 class = "how-to">Q 一度に出せるゴミの量は？</h3>
          <span>+</span>
          <div class = "answer">
            <p>一度に出せるゴミの量は、一人につき2袋、3人以上の世帯で5袋までとなっています。それ以上の量を出されると、一時多量のゴミとしてルール違反になりますので収集されません。<br>引越しなどでどうしても大量のゴミを処分する場合は、自分で市の処理施設に持ち込むか、市の許可を持った業者に収集を依頼してください</p>
          </div> 
        </div>
      </ul>
      <ul id = "how-to-list">
        <div class = "how-to-item">
          <h3 class = "how-to">Q 台風が接近時のごみ収集</h3>
          <span>+</span>
          <div class = "answer">
            <p></p>
          </div> 
        </div>
      </ul>
      <ul id = "how-to-list">
        <div class = "how-to-item">
          <h3 class = "how-to">Q 生ごみ処理機の助成金について</h3>
          <span>+</span>
          <div class = "answer">
            <p></p>
          </div> 
        </div>
      </ul>
      <ul id = "how-to-list">
        <div class = "how-to-item">
          <h3 class = "how-to">Q 袋に入らないものはどうしたらいいのか？</h3>
          <span>+</span>
          <div class = "answer">
            <p></p>
          </div> 
        </div>
      </ul>
    </div>
  </div> 
  <div class = "bring-in-wrapper"> 
    <div id = "bring-in">
      <p>ゴミの持ち込みについて<p>
        <table >
          <tr>
            <th scope = "col">事業所</th>
            <th scope = "col">曜日</th>
            <th scope = "col">受入時間</th>
            <th scope = "col">電話番号</th>
            <th scope = "col">注意事項</th>
          </tr>
          <tr> 
            <td> 芦北町清掃センター</td> 
            <td> 平日 </td> 
            <td> １３時〜１６時</td> 
            <td> ８６−０２７７</td> 
            <td> 毎週第３日曜日のみ 受入時間が９時〜１２時までになります。</td> 
          </tr> 
          <tr> 
            <td> 田浦事業所</td> 
            <td> 火曜・木曜 </td> 
            <td> ０９時〜１２時</td> 
            <td> ８７−１８８１</td> 
            <td> </td>   
          </tr> 
        </table>  
    </div>
    <div class="trash-map">
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12410.91028106302!2d130.50191405003713!3d32.283336856836506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353f99851f507109%3A0xd1dc6297bb2d3ca6!2z6Iqm5YyX55S65riF5o6D44K744Oz44K_44O8IOiKpuWMl-S6i-alreaJgA!5e0!3m2!1sja!2sjp!4v1577860184355!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        <a href = "https://goo.gl/maps/JhXWdeNeQrkAaqgz7" class = "google-map">Googlemapで見る</a>
      </div>
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14965.873817798492!2d130.5137060639069!3d32.37035567890014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353f84d6cde9d5f1%3A0xab5015a73766f185!2z6Iqm5YyX55S65riF5o6D44K744Oz44K_44O8IOeUsOa1puS6i-alreaJgA!5e0!3m2!1sja!2sjp!4v1577861844077!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        <a href = "https://goo.gl/maps/qDK8k8Te2ijqRKnc8" class = "google-map">Googlemapで見る</a>
      </div>
    </div>       
  </div>
  <div class = "appliance-wrapper ">
    <div id = "appliance" >
    <p>家電４品目について</p>
    <table >
      <tr>
        <td colspan="4">リサイクル料金（平成２４年４月現在）</td>
        <td>運搬料金</td>
      </tr>
      <tr>
        <td rowspan="3">テレビ<br />
        （ブラウン管、液晶、プラズマ式）</td>
        <td>区分なし</td>
        <td >2,835円～3,200円</td>
        <td rowspan="9">リサイクル券<br />
        （払込手数料）<br />
        １２０円</td>
        <td rowspan="3">1,000円</td>
      </tr>
      <tr>
        <td >１６型以上</td>
        <td >2,835円～3,795円</td>
      </tr>
      <tr>
        <td>１５型以下</td>
        <td>1,785円～3,270円</td>
      </tr>
      <tr>
        <td>洗濯機</td>
        <td>区分なし</td>
        <td>2,520円～3,444円</td>
        <td>1,000円</td>
      </tr>
      <tr>
        <td>衣類乾燥機</td>
        <td>区分なし</td>
        <td >2,520円～3,444円</td>
        <td >1,000円</td>
      </tr>
      <tr>
        <td>エアコン</td>
        <td>区分なし</td>
        <td>2,100円～15,750円</td>
        <td>1,200円</td>
      </tr>
      <tr>
        <td rowspan="3">冷蔵庫</td>
        <td>区分なし</td>
        <td>4,830円～</td>
        <td rowspan="3">1,500円</td>
      </tr>
      <tr>
        <td >１７１リットル以上</td>
        <td >4,830円～5,869円</td>
      </tr>
      <tr>
        <td >１７０リットル以下</td>
        <td >3,780円～5,344円</td>
      </tr>
    </table>
    </div>
  </div>
  <div class = "contact-wrapper"> 
    <div id = "contact">
      <p>問い合わせ</P>
      <table >
          <tr>
            <th scope = "col">問い合わせ先</th>
            <th scope = "col">電話番号</th>
            <th scope = "col">注意事項</th>
          </tr>
          <tr> 
            <td> 芦北町清掃センター</td> 
            <td> ８６−０２７７</td> 
            <td> 焼却施設がないので、持ち込む「燃やすゴミ」が１００ｋｇを超える場合は、<br>水俣芦北広域行政事務クリーンセンター（水俣市築地）へ持ち込んでください。
            </td> 
          </tr> 
          <tr> 
            <td> 水俣芦北広域行政事務組合クリーンセンター</td> 
            <td> ６２−４１０１</td> 
            <td> </td>  
          </tr> 
        </table>  
    </div> 
    <div class="trash-map">
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12410.91028106302!2d130.50191405003713!3d32.283336856836506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353f99851f507109%3A0xd1dc6297bb2d3ca6!2z6Iqm5YyX55S65riF5o6D44K744Oz44K_44O8IOiKpuWMl-S6i-alreaJgA!5e0!3m2!1sja!2sjp!4v1577860184355!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        <a href = "https://goo.gl/maps/JhXWdeNeQrkAaqgz7" class = "google-map">Googlemapで見る</a>
      </div>
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10557.023721107922!2d130.3891127507203!3d32.2157823605336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353fbc2cf4cab3b5%3A0xfe65feab49e0005f!2z5rC05L-j6Iqm5YyX5bqD5Z-f6KGM5pS_5LqL5YuZ57WE5ZCI44Kv44Oq44O844Oz44K744Oz44K_44O8!5e0!3m2!1sja!2sjp!4v1577859626251!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        <a href = "https://goo.gl/maps/tn3LV91EV71zZvBg9" class = "google-map">Googlemapで見る</a>
      </div>
    </div>      
  </div>

app/views/trashes/search.html.erb
<div class = "header">
  <button class = "btn-item">
    <a href = "/" class = "back-btn">TOPページへ戻る</a>
  </button>
</div>
<div class="container">
  <%= form_with(url: search_trashes_path, remote: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "品目
    を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %> 
  <%= render partial: "trash_list" %>
</div>
   

app/views/trashes/show.html.erb
 
<div class = "dictionary-wrapper">
  <div class = "header">
    <button class = "btn-item">
      <a href = "/" class = "back-btn">TOPページへ戻る</a>
    </button>
    <h1>ゴミ分別検索</h1>
  </div>
    <%= form_with(url:search_trashes_path, local: true, method: :get, class: "search-form") do |form| %>
  
      <%= form.text_field :keyword, placeholder: "品目を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
 
  <div id = "trash-list">
     
   
   <%= render partial: 'trash_list' %>
  </div>
  <div class = "page">
    <%= paginate(@trashes)  %>
  </div>
</div>
 